// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwT8-Y3JIvA8uNQzY7QyDVW3Queaw8sU',
    appId: '1:953870159109:web:63f67424530e267ee97b6c',
    messagingSenderId: '953870159109',
    projectId: 'applicazionetestfirebase-7b312',
    authDomain: 'applicazionetestfirebase-7b312.firebaseapp.com',
    databaseURL: 'https://applicazionetestfirebase-7b312-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'applicazionetestfirebase-7b312.firebasestorage.app',
    measurementId: 'G-NX2S5J58XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkYMeaA8sb_H2rCDLs0pRX-uBUv3FosBs',
    appId: '1:953870159109:android:2693cd6fed36b9fee97b6c',
    messagingSenderId: '953870159109',
    projectId: 'applicazionetestfirebase-7b312',
    databaseURL: 'https://applicazionetestfirebase-7b312-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'applicazionetestfirebase-7b312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGGPlj0EA6T3anSs1cUBHccdyislZ0ek',
    appId: '1:953870159109:ios:6f1726811ba61942e97b6c',
    messagingSenderId: '953870159109',
    projectId: 'applicazionetestfirebase-7b312',
    databaseURL: 'https://applicazionetestfirebase-7b312-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'applicazionetestfirebase-7b312.firebasestorage.app',
    iosBundleId: 'com.ivanromeo.applicazioneTestFirebase',
  );

}